const careersData = [
  {
   id: "IT_001",
    title: "Full Stack Developer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Computer Engineering",
    after12: "B.Tech/B.E. in Computer Science or BCA",
    degree: "B.Tech in CS/IT or MCA",
    exams: ["JEE Main", "VITEEE", "CUET"],
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "SQL"],
    salary: { entry: "5-8 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Increasing demand for MERN/MEAN stack and Gen-AI integrated web apps."
  },
  {
    id: "IT_002",
    title: "Data Scientist",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT or Data Analytics",
    after12: "B.Sc in Statistics or B.Tech in CS",
    degree: "M.Tech in Data Science or M.Sc in Statistics",
    exams: ["GATE", "IIT-JAM", "BITSAT"],
    skills: ["Python", "Machine Learning", "R", "Tableau", "Statistics"],
    salary: { entry: "7-12 LPA", mid: "18-30 LPA", senior: "35-60 LPA" },
    future: "Transitioning toward AI-driven predictive modeling and big data synthesis."
  },
  {
    id: "IT_003",
    title: "Cyber Security Analyst",
    category: "IT & Software",
    subCategory: "Cyber Security",
    after10: "Diploma in Cyber Security",
    after12: "B.Tech in IT or B.Sc in Cyber Security",
    degree: "M.Tech in Information Security or Certifications (CEH, CISSP)",
    exams: ["JEE Main", "TANCET", "IPU CET"],
    skills: ["Ethical Hacking", "Network Security", "SIEM", "Firewall Configuration"],
    salary: { entry: "5-9 LPA", mid: "12-20 LPA", senior: "22-40 LPA" },
    future: "High growth due to rising data privacy laws and digital banking threats in India."
  },
  {
    id: "IT_004",
    title: "DevOps Engineer",
    category: "IT & Software",
    subCategory: "DevOps",
    after10: "Diploma in Computer Science",
    after12: "B.Tech/B.E. in CS/IT",
    degree: "B.Tech/MCA with AWS/Azure DevOps Certification",
    exams: ["JEE Main", "SRMJEEE"],
    skills: ["Docker", "Kubernetes", "Jenkins", "Terraform", "CI/CD"],
    salary: { entry: "6-10 LPA", mid: "15-28 LPA", senior: "30-55 LPA" },
    future: "Shifting toward Platform Engineering and DevSecOps for secure automation."
  },
  {
    id: "IT_005",
    title: "Cloud Architect",
    category: "IT & Software",
    subCategory: "Cloud",
    after10: "Diploma in IT",
    after12: "B.Tech in CS or Cloud Computing",
    degree: "B.Tech + Professional Cloud Certification (AWS/Azure/GCP)",
    exams: ["GATE", "JEE Main"],
    skills: ["Cloud Infrastructure", "Microservices", "Python", "Networking"],
    salary: { entry: "8-12 LPA", mid: "20-35 LPA", senior: "40-75 LPA" },
    future: "Massive adoption as Indian enterprises migrate completely to hybrid cloud."
  },
  {
    id: "IT_006",
    title: "AI/ML Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in AI & ML",
    after12: "B.Tech in AI & Data Science",
    degree: "M.Tech in AI or MS in Computer Science",
    exams: ["GATE", "JEE Advanced"],
    skills: ["Deep Learning", "NLP", "PyTorch", "TensorFlow", "Computer Vision"],
    salary: { entry: "8-15 LPA", mid: "22-40 LPA", senior: "45-90 LPA" },
    future: "Explosive growth driven by Generative AI and LLM implementation."
  },
  {
    id: "IT_007",
    title: "Mobile App Developer",
    category: "IT & Software",
    subCategory: "Mobile Development",
    after10: "Diploma in Computer Engineering",
    after12: "B.Tech in IT or BCA",
    degree: "B.Tech or MCA",
    exams: ["JEE Main", "MAH CET"],
    skills: ["Kotlin", "Swift", "Flutter", "React Native", "API Integration"],
    salary: { entry: "4-8 LPA", mid: "10-18 LPA", senior: "20-40 LPA" },
    future: "Evolving into cross-platform development and Super-App ecosystems."
  },
  {
    id: "IT_008",
    title: "Blockchain Developer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Computer Science",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech + Certification in Blockchain Tech",
    exams: ["JEE Main", "MET"],
    skills: ["Solidity", "Ethereum", "Smart Contracts", "Rust", "Cryptography"],
    salary: { entry: "6-10 LPA", mid: "15-25 LPA", senior: "30-60 LPA" },
    future: "Adoption in Supply Chain, FinTech (CBDC), and Web3 applications."
  },
  {
    id: "IT_009",
    title: "Automation QA Engineer",
    category: "IT & Software",
    subCategory: "QA",
    after10: "Diploma in IT",
    after12: "B.Tech in CS or B.Sc IT",
    degree: "B.Tech or BCA",
    exams: ["JEE Main", "COMEDK"],
    skills: ["Selenium", "Java", "Appium", "Cucumber", "API Testing"],
    salary: { entry: "4-7 LPA", mid: "9-16 LPA", senior: "18-35 LPA" },
    future: "Increasing use of AI for automated test script generation (Autonomous Testing)."
  },
  {
    id: "IT_010",
    title: "Technical Product Manager",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Vocational course in Management",
    after12: "B.Tech in any stream",
    degree: "MBA (IT/Operations) + B.Tech",
    exams: ["CAT", "XAT", "GMAT"],
    skills: ["Product Roadmap", "Agile", "User Research", "Data Analytics"],
    salary: { entry: "10-18 LPA", mid: "22-45 LPA", senior: "50-1.2 Cr" },
    future: "Critical role in Indian SaaS and E-commerce scaling."
  },
  {
    id: "IT_011",
    title: "Site Reliability Engineer (SRE)",
    category: "IT & Software",
    subCategory: "DevOps",
    after10: "Diploma in CS",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech CS or MCA",
    exams: ["JEE Main", "GATE"],
    skills: ["System Administration", "Python", "Monitoring Tools", "Automation"],
    salary: { entry: "8-14 LPA", mid: "18-32 LPA", senior: "35-65 LPA" },
    future: "Focus on 'Error Budgets' and ultra-high availability for global apps."
  },
  {
    id: "IT_012",
    title: "UI/UX Designer",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Foundation in Fine Arts",
    after12: "B.Des in Interaction Design",
    degree: "B.Des or M.Des (User Experience)",
    exams: ["UCEED", "CEED", "NID DAT"],
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "Wireframing"],
    salary: { entry: "4-8 LPA", mid: "12-22 LPA", senior: "25-50 LPA" },
    future: "Expanding into AR/VR interface design and Voice UI."
  },
  {
    id: "IT_013",
    title: "Big Data Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech or M.Tech (Big Data)",
    exams: ["GATE", "JEE Main"],
    skills: ["Hadoop", "Spark", "Scala", "NoSQL", "Data Pipelines"],
    salary: { entry: "6-12 LPA", mid: "16-30 LPA", senior: "32-60 LPA" },
    future: "Shift toward real-time stream processing and Snowflake/Databricks."
  },
  {
    id: "IT_014",
    title: "Network Architect",
    category: "IT & Software",
    subCategory: "IT Support",
    after10: "Diploma in Electronics/CS",
    after12: "B.Tech in ECE/CS",
    degree: "B.Tech + CCIE Certification",
    exams: ["JEE Main", "GATE"],
    skills: ["Cisco Routing", "Network Design", "SD-WAN", "Virtualization"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Emergence of 6G and software-defined networking (SDN)."
  },
  {
    id: "IT_015",
    title: "Embedded Systems Engineer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Electronics",
    after12: "B.Tech in ECE/EEE",
    degree: "B.Tech/M.Tech in Embedded Systems",
    exams: ["GATE", "JEE Main"],
    skills: ["C/C++", "RTOS", "Microcontrollers", "IoT Protocols"],
    salary: { entry: "4-8 LPA", mid: "10-20 LPA", senior: "22-45 LPA" },
    future: "Growth in EV (Electric Vehicle) software and Smart Cities IoT."
  },
  {
    id: "IT_016",
    title: "Game Developer",
    category: "IT & Software",
    subCategory: "Gaming",
    after10: "Diploma in Multimedia/IT",
    after12: "B.Tech in CS or B.Sc in Gaming",
    degree: "B.Tech or B.Sc Animation & Gaming",
    exams: ["JEE Main", "NID DAT"],
    skills: ["Unity 3D", "Unreal Engine", "C#", "C++", "Physics Engines"],
    salary: { entry: "4-7 LPA", mid: "9-18 LPA", senior: "20-40 LPA" },
    future: "Expansion of India's mobile gaming market and Esports tech."
  },
  {
    id: "IT_017",
    title: "SAP Consultant",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Diploma in Business/IT",
    after12: "B.Tech or B.Com + SAP Training",
    degree: "B.Tech/MBA + SAP Certification (ABAP/FICO)",
    exams: ["CAT", "SAP Certification"],
    skills: ["SAP ERP", "ABAP", "Business Processes", "HANA Database"],
    salary: { entry: "5-8 LPA", mid: "12-25 LPA", senior: "28-55 LPA" },
    future: "Migration to SAP S/4HANA Cloud in the manufacturing sector."
  },
  {
    id: "IT_018",
    title: "Business Intelligence (BI) Developer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT",
    after12: "BCA or B.Sc IT",
    degree: "B.Tech or MCA",
    exams: ["IPU CET", "CUET"],
    skills: ["Power BI", "SQL", "DAX", "Data Warehousing", "ETL"],
    salary: { entry: "4-8 LPA", mid: "10-18 LPA", senior: "20-35 LPA" },
    future: "Integration of Natural Language Querying (NLQ) in BI tools."
  },
  {
    id: "IT_019",
    title: "Solutions Architect",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in CS",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech/MCA with 8+ years experience",
    exams: ["JEE Main", "GATE"],
    skills: ["System Design", "Cloud Architecture", "SDLC", "Stakeholder Mgmt"],
    salary: { entry: "12-18 LPA", mid: "25-45 LPA", senior: "50-95 LPA" },
    future: "Demand for cloud-native and serverless architecture expertise."
  },
  {
    id: "IT_020",
    title: "Penetration Tester",
    category: "IT & Software",
    subCategory: "Cyber Security",
    after10: "Diploma in IT",
    after12: "B.Sc/B.Tech in CS",
    degree: "B.Tech + OSCP/LPT Certification",
    exams: ["JEE Main", "VITEEE"],
    skills: ["Vulnerability Assessment", "Metasploit", "Python", "Web App Security"],
    salary: { entry: "5-10 LPA", mid: "12-24 LPA", senior: "26-50 LPA" },
    future: "Critical need for 'Red Teaming' in FinTech and Healthcare."
  },
  {
    id: "IT_021",
    title: "Front End Engineer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Web Design",
    after12: "BCA or B.Tech IT",
    degree: "B.Tech or MCA",
    exams: ["CUET", "JEE Main"],
    skills: ["React", "Vue.js", "TypeScript", "Tailwind CSS", "Next.js"],
    salary: { entry: "4-7 LPA", mid: "10-18 LPA", senior: "20-38 LPA" },
    future: "Shift toward 3D web (Three.js) and performance-focused frameworks."
  },
  {
    id: "IT_022",
    title: "Back End Engineer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in CS",
    after12: "B.Tech or BCA",
    degree: "B.Tech/B.E. Computer Science",
    exams: ["JEE Main", "KIITEE"],
    skills: ["Java", "Go", "Python", "PostgreSQL", "Redis"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Increasing move toward Go (Golang) and Rust for high-scale microservices."
  },
  {
    id: "IT_023",
    title: "Information Technology Manager",
    category: "IT & Software",
    subCategory: "IT Support",
    after10: "Diploma in IT",
    after12: "B.Tech/BCA",
    degree: "MBA in IT Management + B.Tech",
    exams: ["CAT", "MAT", "NMAT"],
    skills: ["Project Management", "ITIL", "Budgeting", "Vendor Management"],
    salary: { entry: "8-12 LPA", mid: "15-28 LPA", senior: "30-55 LPA" },
    future: "Managing remote IT infrastructure and distributed teams."
  },
  {
    id: "IT_024",
    title: "Data Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech or M.Tech CS",
    exams: ["GATE", "JEE Main"],
    skills: ["SQL", "Python", "Airflow", "Kafka", "AWS Redshift"],
    salary: { entry: "6-11 LPA", mid: "15-28 LPA", senior: "30-55 LPA" },
    future: "Growth in 'Data Mesh' and automated data cataloging."
  },
  {
    id: "IT_025",
    title: "Computer Vision Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in Electronics",
    after12: "B.Tech in CS/AI",
    degree: "M.Tech in AI/Robotics or PhD",
    exams: ["GATE", "JEE Advanced"],
    skills: ["OpenCV", "TensorFlow", "Image Processing", "C++"],
    salary: { entry: "7-13 LPA", mid: "18-35 LPA", senior: "38-80 LPA" },
    future: "Applications in autonomous drones, medical imaging, and security."
  },
  {
    id: "IT_026",
    title: "Application Support Engineer",
    category: "IT & Software",
    subCategory: "IT Support",
    after10: "Diploma in CS",
    after12: "BCA or B.Sc IT",
    degree: "MCA or B.Tech",
    exams: ["CUET", "MAH CET"],
    skills: ["SQL", "Linux Commands", "Shell Scripting", "Troubleshooting"],
    salary: { entry: "3-6 LPA", mid: "7-14 LPA", senior: "15-25 LPA" },
    future: "Transitioning to Site Reliability and Automated Monitoring roles."
  },
  {
    id: "IT_027",
    title: "Blockchain Architect",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in IT",
    after12: "B.Tech in CS",
    degree: "B.Tech + Advanced Blockchain Certifications",
    exams: ["JEE Main", "GATE"],
    skills: ["Hyperledger", "System Design", "Consensus Algorithms", "Security"],
    salary: { entry: "15-25 LPA", mid: "30-50 LPA", senior: "60-1.1 Cr" },
    future: "Enterprise-grade decentralized networks for trade and governance."
  },
  {
    id: "IT_028",
    title: "Robotic Process Automation (RPA) Developer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in IT",
    after12: "B.Tech/BCA",
    degree: "B.Tech or MCA",
    exams: ["JEE Main", "SRMJEEE"],
    skills: ["UiPath", "Blue Prism", "Automation Anywhere", "Python"],
    salary: { entry: "4-8 LPA", mid: "10-18 LPA", senior: "20-35 LPA" },
    future: "Integrating 'Intelligent Automation' (AI + RPA) for complex tasks."
  },
  {
    id: "IT_029",
    title: "ERP Technical Lead",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Diploma in Business/IT",
    after12: "B.Tech or B.Com",
    degree: "B.Tech + Oracle/SAP Technical Certification",
    exams: ["GATE", "Oracle Certification"],
    skills: ["PL/SQL", "Oracle Apps", "Java", "Workflow Management"],
    salary: { entry: "6-10 LPA", mid: "14-25 LPA", senior: "28-50 LPA" },
    future: "Migrating legacy ERPs to AI-enhanced cloud platforms."
  },
  {
    id: "IT_030",
    title: "SaaS Sales Engineer",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Foundation in Commerce/IT",
    after12: "B.Tech or B.Sc IT",
    degree: "B.Tech + MBA (Marketing/International Business)",
    exams: ["CAT", "NMAT"],
    skills: ["Product Demo", "Technical Presentation", "CRM", "API Knowledge"],
    salary: { entry: "7-12 LPA", mid: "15-30 LPA", senior: "35-65 LPA" },
    future: "Booming role as Indian SaaS startups expand to US/EU markets."
  }
] 
