const careersData = [
  {
   id: "IT_001",
    title: "Full Stack Developer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Computer Engineering",
    after12: "B.Tech/B.E. in Computer Science or BCA",
    degree: "B.Tech in CS/IT or MCA",
    exams: ["JEE Main", "VITEEE", "CUET"],
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "SQL"],
    salary: { entry: "5-8 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Increasing demand for MERN/MEAN stack and Gen-AI integrated web apps."
  },
  {
    id: "IT_002",
    title: "Data Scientist",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT or Data Analytics",
    after12: "B.Sc in Statistics or B.Tech in CS",
    degree: "M.Tech in Data Science or M.Sc in Statistics",
    exams: ["GATE", "IIT-JAM", "BITSAT"],
    skills: ["Python", "Machine Learning", "R", "Tableau", "Statistics"],
    salary: { entry: "7-12 LPA", mid: "18-30 LPA", senior: "35-60 LPA" },
    future: "Transitioning toward AI-driven predictive modeling and big data synthesis."
  },
  {
    id: "IT_003",
    title: "Cyber Security Analyst",
    category: "IT & Software",
    subCategory: "Cyber Security",
    after10: "Diploma in Cyber Security",
    after12: "B.Tech in IT or B.Sc in Cyber Security",
    degree: "M.Tech in Information Security or Certifications (CEH, CISSP)",
    exams: ["JEE Main", "TANCET", "IPU CET"],
    skills: ["Ethical Hacking", "Network Security", "SIEM", "Firewall Configuration"],
    salary: { entry: "5-9 LPA", mid: "12-20 LPA", senior: "22-40 LPA" },
    future: "High growth due to rising data privacy laws and digital banking threats in India."
  },
  {
    id: "IT_004",
    title: "DevOps Engineer",
    category: "IT & Software",
    subCategory: "DevOps",
    after10: "Diploma in Computer Science",
    after12: "B.Tech/B.E. in CS/IT",
    degree: "B.Tech/MCA with AWS/Azure DevOps Certification",
    exams: ["JEE Main", "SRMJEEE"],
    skills: ["Docker", "Kubernetes", "Jenkins", "Terraform", "CI/CD"],
    salary: { entry: "6-10 LPA", mid: "15-28 LPA", senior: "30-55 LPA" },
    future: "Shifting toward Platform Engineering and DevSecOps for secure automation."
  },
  {
    id: "IT_005",
    title: "Cloud Architect",
    category: "IT & Software",
    subCategory: "Cloud",
    after10: "Diploma in IT",
    after12: "B.Tech in CS or Cloud Computing",
    degree: "B.Tech + Professional Cloud Certification (AWS/Azure/GCP)",
    exams: ["GATE", "JEE Main"],
    skills: ["Cloud Infrastructure", "Microservices", "Python", "Networking"],
    salary: { entry: "8-12 LPA", mid: "20-35 LPA", senior: "40-75 LPA" },
    future: "Massive adoption as Indian enterprises migrate completely to hybrid cloud."
  },
  {
    id: "IT_006",
    title: "AI/ML Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in AI & ML",
    after12: "B.Tech in AI & Data Science",
    degree: "M.Tech in AI or MS in Computer Science",
    exams: ["GATE", "JEE Advanced"],
    skills: ["Deep Learning", "NLP", "PyTorch", "TensorFlow", "Computer Vision"],
    salary: { entry: "8-15 LPA", mid: "22-40 LPA", senior: "45-90 LPA" },
    future: "Explosive growth driven by Generative AI and LLM implementation."
  },
  {
    id: "IT_007",
    title: "Mobile App Developer",
    category: "IT & Software",
    subCategory: "Mobile Development",
    after10: "Diploma in Computer Engineering",
    after12: "B.Tech in IT or BCA",
    degree: "B.Tech or MCA",
    exams: ["JEE Main", "MAH CET"],
    skills: ["Kotlin", "Swift", "Flutter", "React Native", "API Integration"],
    salary: { entry: "4-8 LPA", mid: "10-18 LPA", senior: "20-40 LPA" },
    future: "Evolving into cross-platform development and Super-App ecosystems."
  },
  {
    id: "IT_008",
    title: "Blockchain Developer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Computer Science",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech + Certification in Blockchain Tech",
    exams: ["JEE Main", "MET"],
    skills: ["Solidity", "Ethereum", "Smart Contracts", "Rust", "Cryptography"],
    salary: { entry: "6-10 LPA", mid: "15-25 LPA", senior: "30-60 LPA" },
    future: "Adoption in Supply Chain, FinTech (CBDC), and Web3 applications."
  },
  {
    id: "IT_009",
    title: "Automation QA Engineer",
    category: "IT & Software",
    subCategory: "QA",
    after10: "Diploma in IT",
    after12: "B.Tech in CS or B.Sc IT",
    degree: "B.Tech or BCA",
    exams: ["JEE Main", "COMEDK"],
    skills: ["Selenium", "Java", "Appium", "Cucumber", "API Testing"],
    salary: { entry: "4-7 LPA", mid: "9-16 LPA", senior: "18-35 LPA" },
    future: "Increasing use of AI for automated test script generation (Autonomous Testing)."
  },
  {
    id: "IT_010",
    title: "Technical Product Manager",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Vocational course in Management",
    after12: "B.Tech in any stream",
    degree: "MBA (IT/Operations) + B.Tech",
    exams: ["CAT", "XAT", "GMAT"],
    skills: ["Product Roadmap", "Agile", "User Research", "Data Analytics"],
    salary: { entry: "10-18 LPA", mid: "22-45 LPA", senior: "50-1.2 Cr" },
    future: "Critical role in Indian SaaS and E-commerce scaling."
  },
  {
    id: "IT_011",
    title: "Site Reliability Engineer (SRE)",
    category: "IT & Software",
    subCategory: "DevOps",
    after10: "Diploma in CS",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech CS or MCA",
    exams: ["JEE Main", "GATE"],
    skills: ["System Administration", "Python", "Monitoring Tools", "Automation"],
    salary: { entry: "8-14 LPA", mid: "18-32 LPA", senior: "35-65 LPA" },
    future: "Focus on 'Error Budgets' and ultra-high availability for global apps."
  },
  {
    id: "IT_012",
    title: "UI/UX Designer",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Foundation in Fine Arts",
    after12: "B.Des in Interaction Design",
    degree: "B.Des or M.Des (User Experience)",
    exams: ["UCEED", "CEED", "NID DAT"],
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "Wireframing"],
    salary: { entry: "4-8 LPA", mid: "12-22 LPA", senior: "25-50 LPA" },
    future: "Expanding into AR/VR interface design and Voice UI."
  },
  {
    id: "IT_013",
    title: "Big Data Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech or M.Tech (Big Data)",
    exams: ["GATE", "JEE Main"],
    skills: ["Hadoop", "Spark", "Scala", "NoSQL", "Data Pipelines"],
    salary: { entry: "6-12 LPA", mid: "16-30 LPA", senior: "32-60 LPA" },
    future: "Shift toward real-time stream processing and Snowflake/Databricks."
  },
  {
    id: "IT_014",
    title: "Network Architect",
    category: "IT & Software",
    subCategory: "IT Support",
    after10: "Diploma in Electronics/CS",
    after12: "B.Tech in ECE/CS",
    degree: "B.Tech + CCIE Certification",
    exams: ["JEE Main", "GATE"],
    skills: ["Cisco Routing", "Network Design", "SD-WAN", "Virtualization"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Emergence of 6G and software-defined networking (SDN)."
  },
  {
    id: "IT_015",
    title: "Embedded Systems Engineer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Electronics",
    after12: "B.Tech in ECE/EEE",
    degree: "B.Tech/M.Tech in Embedded Systems",
    exams: ["GATE", "JEE Main"],
    skills: ["C/C++", "RTOS", "Microcontrollers", "IoT Protocols"],
    salary: { entry: "4-8 LPA", mid: "10-20 LPA", senior: "22-45 LPA" },
    future: "Growth in EV (Electric Vehicle) software and Smart Cities IoT."
  },
  {
    id: "IT_016",
    title: "Game Developer",
    category: "IT & Software",
    subCategory: "Gaming",
    after10: "Diploma in Multimedia/IT",
    after12: "B.Tech in CS or B.Sc in Gaming",
    degree: "B.Tech or B.Sc Animation & Gaming",
    exams: ["JEE Main", "NID DAT"],
    skills: ["Unity 3D", "Unreal Engine", "C#", "C++", "Physics Engines"],
    salary: { entry: "4-7 LPA", mid: "9-18 LPA", senior: "20-40 LPA" },
    future: "Expansion of India's mobile gaming market and Esports tech."
  },
  {
    id: "IT_017",
    title: "SAP Consultant",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Diploma in Business/IT",
    after12: "B.Tech or B.Com + SAP Training",
    degree: "B.Tech/MBA + SAP Certification (ABAP/FICO)",
    exams: ["CAT", "SAP Certification"],
    skills: ["SAP ERP", "ABAP", "Business Processes", "HANA Database"],
    salary: { entry: "5-8 LPA", mid: "12-25 LPA", senior: "28-55 LPA" },
    future: "Migration to SAP S/4HANA Cloud in the manufacturing sector."
  },
  {
    id: "IT_018",
    title: "Business Intelligence (BI) Developer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT",
    after12: "BCA or B.Sc IT",
    degree: "B.Tech or MCA",
    exams: ["IPU CET", "CUET"],
    skills: ["Power BI", "SQL", "DAX", "Data Warehousing", "ETL"],
    salary: { entry: "4-8 LPA", mid: "10-18 LPA", senior: "20-35 LPA" },
    future: "Integration of Natural Language Querying (NLQ) in BI tools."
  },
  {
    id: "IT_019",
    title: "Solutions Architect",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in CS",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech/MCA with 8+ years experience",
    exams: ["JEE Main", "GATE"],
    skills: ["System Design", "Cloud Architecture", "SDLC", "Stakeholder Mgmt"],
    salary: { entry: "12-18 LPA", mid: "25-45 LPA", senior: "50-95 LPA" },
    future: "Demand for cloud-native and serverless architecture expertise."
  },
  {
    id: "IT_020",
    title: "Penetration Tester",
    category: "IT & Software",
    subCategory: "Cyber Security",
    after10: "Diploma in IT",
    after12: "B.Sc/B.Tech in CS",
    degree: "B.Tech + OSCP/LPT Certification",
    exams: ["JEE Main", "VITEEE"],
    skills: ["Vulnerability Assessment", "Metasploit", "Python", "Web App Security"],
    salary: { entry: "5-10 LPA", mid: "12-24 LPA", senior: "26-50 LPA" },
    future: "Critical need for 'Red Teaming' in FinTech and Healthcare."
  },
  {
    id: "IT_021",
    title: "Front End Engineer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in Web Design",
    after12: "BCA or B.Tech IT",
    degree: "B.Tech or MCA",
    exams: ["CUET", "JEE Main"],
    skills: ["React", "Vue.js", "TypeScript", "Tailwind CSS", "Next.js"],
    salary: { entry: "4-7 LPA", mid: "10-18 LPA", senior: "20-38 LPA" },
    future: "Shift toward 3D web (Three.js) and performance-focused frameworks."
  },
  {
    id: "IT_022",
    title: "Back End Engineer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in CS",
    after12: "B.Tech or BCA",
    degree: "B.Tech/B.E. Computer Science",
    exams: ["JEE Main", "KIITEE"],
    skills: ["Java", "Go", "Python", "PostgreSQL", "Redis"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Increasing move toward Go (Golang) and Rust for high-scale microservices."
  },
  {
    id: "IT_023",
    title: "Information Technology Manager",
    category: "IT & Software",
    subCategory: "IT Support",
    after10: "Diploma in IT",
    after12: "B.Tech/BCA",
    degree: "MBA in IT Management + B.Tech",
    exams: ["CAT", "MAT", "NMAT"],
    skills: ["Project Management", "ITIL", "Budgeting", "Vendor Management"],
    salary: { entry: "8-12 LPA", mid: "15-28 LPA", senior: "30-55 LPA" },
    future: "Managing remote IT infrastructure and distributed teams."
  },
  {
    id: "IT_024",
    title: "Data Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in IT",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech or M.Tech CS",
    exams: ["GATE", "JEE Main"],
    skills: ["SQL", "Python", "Airflow", "Kafka", "AWS Redshift"],
    salary: { entry: "6-11 LPA", mid: "15-28 LPA", senior: "30-55 LPA" },
    future: "Growth in 'Data Mesh' and automated data cataloging."
  },
  {
    id: "IT_025",
    title: "Computer Vision Engineer",
    category: "IT & Software",
    subCategory: "Data & AI",
    after10: "Diploma in Electronics",
    after12: "B.Tech in CS/AI",
    degree: "M.Tech in AI/Robotics or PhD",
    exams: ["GATE", "JEE Advanced"],
    skills: ["OpenCV", "TensorFlow", "Image Processing", "C++"],
    salary: { entry: "7-13 LPA", mid: "18-35 LPA", senior: "38-80 LPA" },
    future: "Applications in autonomous drones, medical imaging, and security."
  },
  {
    id: "IT_026",
    title: "Application Support Engineer",
    category: "IT & Software",
    subCategory: "IT Support",
    after10: "Diploma in CS",
    after12: "BCA or B.Sc IT",
    degree: "MCA or B.Tech",
    exams: ["CUET", "MAH CET"],
    skills: ["SQL", "Linux Commands", "Shell Scripting", "Troubleshooting"],
    salary: { entry: "3-6 LPA", mid: "7-14 LPA", senior: "15-25 LPA" },
    future: "Transitioning to Site Reliability and Automated Monitoring roles."
  },
  {
    id: "IT_027",
    title: "Blockchain Architect",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in IT",
    after12: "B.Tech in CS",
    degree: "B.Tech + Advanced Blockchain Certifications",
    exams: ["JEE Main", "GATE"],
    skills: ["Hyperledger", "System Design", "Consensus Algorithms", "Security"],
    salary: { entry: "15-25 LPA", mid: "30-50 LPA", senior: "60-1.1 Cr" },
    future: "Enterprise-grade decentralized networks for trade and governance."
  },
  {
    id: "IT_028",
    title: "Robotic Process Automation (RPA) Developer",
    category: "IT & Software",
    subCategory: "Software Development",
    after10: "Diploma in IT",
    after12: "B.Tech/BCA",
    degree: "B.Tech or MCA",
    exams: ["JEE Main", "SRMJEEE"],
    skills: ["UiPath", "Blue Prism", "Automation Anywhere", "Python"],
    salary: { entry: "4-8 LPA", mid: "10-18 LPA", senior: "20-35 LPA" },
    future: "Integrating 'Intelligent Automation' (AI + RPA) for complex tasks."
  },
  {
    id: "IT_029",
    title: "ERP Technical Lead",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Diploma in Business/IT",
    after12: "B.Tech or B.Com",
    degree: "B.Tech + Oracle/SAP Technical Certification",
    exams: ["GATE", "Oracle Certification"],
    skills: ["PL/SQL", "Oracle Apps", "Java", "Workflow Management"],
    salary: { entry: "6-10 LPA", mid: "14-25 LPA", senior: "28-50 LPA" },
    future: "Migrating legacy ERPs to AI-enhanced cloud platforms."
  },
  {
    id: "IT_030",
    title: "SaaS Sales Engineer",
    category: "IT & Software",
    subCategory: "Product",
    after10: "Foundation in Commerce/IT",
    after12: "B.Tech or B.Sc IT",
    degree: "B.Tech + MBA (Marketing/International Business)",
    exams: ["CAT", "NMAT"],
    skills: ["Product Demo", "Technical Presentation", "CRM", "API Knowledge"],
    salary: { entry: "7-12 LPA", mid: "15-30 LPA", senior: "35-65 LPA" },
    future: "Booming role as Indian SaaS startups expand to US/EU markets."
  },
  {
    id: "MED_001",
    title: "General Surgeon",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS (5.5 Years)",
    degree: "MS (Master of Surgery)",
    exams: ["NEET-UG", "NEET-PG", "INI-CET"],
    skills: ["Surgical Precision", "Patient Care", "Diagnosis", "Emergency Response"],
    salary: { entry: "12-18 LPA", mid: "25-45 LPA", senior: "60-90 LPA" },
    future: "Advancement into Robotic-Assisted Surgery and Minimally Invasive techniques."
  },
  {
    id: "MED_002",
    title: "Cardiologist",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "DM in Cardiology",
    exams: ["NEET-UG", "NEET-PG", "NEET-SS"],
    skills: ["Echocardiography", "Angiography", "ECG Analysis", "Interventional Cardiology"],
    salary: { entry: "15-22 LPA", mid: "35-60 LPA", senior: "80 LPA - 1.5 Cr" },
    future: "Focus on AI-driven cardiac monitoring and personalized heart-failure management."
  },
  {
    id: "MED_003",
    title: "Radiologist",
    category: "Medical & Healthcare",
    subCategory: "Diagnostics",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "MD in Radiology",
    exams: ["NEET-UG", "NEET-PG"],
    skills: ["Image Interpretation", "CT/MRI Scanning", "Ultrasonography", "Radiation Safety"],
    salary: { entry: "18-25 LPA", mid: "40-70 LPA", senior: "80 LPA - 1.2 Cr" },
    future: "Increasing integration of AI for automated lesion detection and Teleradiology."
  },
  {
    id: "MED_004",
    title: "Clinical Pharmacist",
    category: "Medical & Healthcare",
    subCategory: "Pharma",
    after10: "Secondary School Education",
    after12: "B.Pharm or D.Pharm",
    degree: "Pharm.D (Doctor of Pharmacy)",
    exams: ["GPAT", "NIPER JEE", "CUET"],
    skills: ["Drug Interaction Analysis", "Patient Counseling", "Pharmacovigilance"],
    salary: { entry: "3-5 LPA", mid: "7-12 LPA", senior: "15-25 LPA" },
    future: "Expansion into Clinical Research and Specialized Therapy Management."
  },
  {
    id: "MED_005",
    title: "Physiotherapist",
    category: "Medical & Healthcare",
    subCategory: "Allied Health",
    after10: "Secondary School Education",
    after12: "BPT (Bachelor of Physiotherapy)",
    degree: "MPT (Master of Physiotherapy)",
    exams: ["IPU CET", "CPNET", "IEMJEE"],
    skills: ["Manual Therapy", "Exercise Physiology", "Rehabilitation", "Anatomy Knowledge"],
    salary: { entry: "3-6 LPA", mid: "8-15 LPA", senior: "18-30 LPA" },
    future: "Rising demand in Sports Medicine and Geriatric rehabilitation tech."
  },
  {
    id: "MED_006",
    title: "Hospital Administrator",
    category: "Medical & Healthcare",
    subCategory: "Administration",
    after10: "Secondary School Education",
    after12: "BBA or B.Sc in Healthcare Management",
    degree: "MHA (Master of Hospital Administration) or MBA (Healthcare)",
    exams: ["CAT", "MAT", "CMAT"],
    skills: ["Operations Management", "Healthcare Laws", "Inventory Control", "Leadership"],
    salary: { entry: "5-9 LPA", mid: "12-25 LPA", senior: "30-60 LPA" },
    future: "Growth in Digital Health transformation and Lean Hospital management."
  },
  {
    id: "MED_007",
    title: "Critical Care Nurse",
    category: "Medical & Healthcare",
    subCategory: "Nursing",
    after10: "Secondary School Education",
    after12: "B.Sc Nursing",
    degree: "M.Sc in Critical Care Nursing",
    exams: ["AIIMS B.Sc Nursing", "RUHS", "NEET (some states)"],
    skills: ["Ventilator Management", "Patient Monitoring", "ACLS/BLS", "Stress Management"],
    salary: { entry: "3-5 LPA", mid: "6-10 LPA", senior: "12-20 LPA" },
    future: "Specialization in remote ICU monitoring and advanced trauma care."
  },
  {
    id: "MED_008",
    title: "Medical Lab Technologist",
    category: "Medical & Healthcare",
    subCategory: "Paramedical",
    after10: "DMLT (Diploma)",
    after12: "BMLT (Bachelor of Medical Lab Technology)",
    degree: "M.Sc in MLT",
    exams: ["CUET", "State Paramedical Boards"],
    skills: ["Hematology", "Microbiology", "Lab Equipment Calibration", "Pathology"],
    salary: { entry: "2.5-4 LPA", mid: "5-9 LPA", senior: "10-18 LPA" },
    future: "Shift toward Molecular Diagnostics and automated high-throughput labs."
  },
  {
    id: "MED_009",
    title: "Dental Surgeon",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "BDS (Bachelor of Dental Surgery)",
    degree: "MDS (Master of Dental Surgery)",
    exams: ["NEET-UG", "NEET-MDS"],
    skills: ["Oral Surgery", "Orthodontics", "Patient Communication", "Manual Dexterity"],
    salary: { entry: "4-8 LPA", mid: "10-20 LPA", senior: "25-50 LPA" },
    future: "Growth in Cosmetic Dentistry and 3D-printed Dental Implants."
  },
  {
    id: "MED_010",
    title: "Anesthesiologist",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "MD in Anesthesia",
    exams: ["NEET-UG", "NEET-PG"],
    skills: ["Pain Management", "Vital Sign Monitoring", "Intubation", "Critical Care"],
    salary: { entry: "12-18 LPA", mid: "25-45 LPA", senior: "50-80 LPA" },
    future: "Evolution into Perioperative Medicine and Pain Management clinics."
  },
  {
    id: "MED_011",
    title: "Occupational Therapist",
    category: "Medical & Healthcare",
    subCategory: "Allied Health",
    after10: "Secondary School Education",
    after12: "BOT (Bachelor of Occupational Therapy)",
    degree: "MOT (Master of Occupational Therapy)",
    exams: ["SVNIRTAR", "AIIPMR"],
    skills: ["Cognitive Rehabilitation", "Pediatric Therapy", "Adaptive Equipment"],
    salary: { entry: "3.5-6 LPA", mid: "8-15 LPA", senior: "18-28 LPA" },
    future: "Expanding scope in Mental Health and Ergonomic workplace design."
  },
  {
    id: "MED_012",
    title: "Optometrist",
    category: "Medical & Healthcare",
    subCategory: "Allied Health",
    after10: "Diploma in Optometry",
    after12: "B.Optom (Bachelor of Optometry)",
    degree: "M.Optom",
    exams: ["AIIMS B.Sc Entrance", "EYECET"],
    skills: ["Vision Testing", "Contact Lens Fitting", "Binocular Vision", "Ocular Diseases"],
    salary: { entry: "3-5 LPA", mid: "7-12 LPA", senior: "15-22 LPA" },
    future: "Focus on myopia control and advanced refractive surgery assistance."
  },
  {
    id: "MED_013",
    title: "Pediatrician",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "MD in Pediatrics",
    exams: ["NEET-UG", "NEET-PG"],
    skills: ["Child Psychology", "Neonatal Care", "Vaccination Protocols"],
    salary: { entry: "10-15 LPA", mid: "20-35 LPA", senior: "40-75 LPA" },
    future: "Emphasis on Genetic Screening and Pediatric superspecialties."
  },
  {
    id: "MED_014",
    title: "Medical Microbiologist",
    category: "Medical & Healthcare",
    subCategory: "Diagnostics",
    after10: "Secondary School Education",
    after12: "B.Sc Microbiology or MBBS",
    degree: "MD or M.Sc in Medical Microbiology",
    exams: ["NEET-PG", "IIT-JAM", "CUET"],
    skills: ["Bacteriology", "Virology", "Infection Control", "Culture Techniques"],
    salary: { entry: "4-7 LPA", mid: "9-16 LPA", senior: "20-35 LPA" },
    future: "Critical role in Pandemics management and Anti-Microbial Resistance research."
  },
  {
    id: "MED_015",
    title: "Nutritionist / Dietician",
    category: "Medical & Healthcare",
    subCategory: "Allied Health",
    after10: "Secondary School Education",
    after12: "B.Sc Home Science / Nutrition",
    degree: "M.Sc in Food and Nutrition / RD (Registered Dietician)",
    exams: ["IDA Exam", "CUET"],
    skills: ["Meal Planning", "Metabolic Disorders Knowledge", "Counseling"],
    salary: { entry: "2.5-4.5 LPA", mid: "6-12 LPA", senior: "15-25 LPA" },
    future: "Growth in Nutrigenomics and personalized clinical nutrition."
  },
  {
    id: "MED_016",
    title: "Biomedical Engineer",
    category: "Medical & Healthcare",
    subCategory: "Allied Health",
    after10: "Diploma in Biomedical",
    after12: "B.Tech in Biomedical Engineering",
    degree: "M.Tech in Biomedical Engineering",
    exams: ["JEE Main", "GATE"],
    skills: ["Medical Imaging Systems", "Prosthetics", "Sensors", "Device Calibration"],
    salary: { entry: "4-7 LPA", mid: "10-18 LPA", senior: "22-40 LPA" },
    future: "Developing wearable health tech and AI-integrated medical devices."
  },
  {
    id: "MED_017",
    title: "Speech Pathologist",
    category: "Medical & Healthcare",
    subCategory: "Allied Health",
    after10: "Secondary School Education",
    after12: "BASLP",
    degree: "MASLP (Master of Audiology & Speech Language Pathology)",
    exams: ["AIIMS", "PGI", "AYJNIHH"],
    skills: ["Speech Assessment", "Audiometry", "Rehabilitative Techniques"],
    salary: { entry: "4-6 LPA", mid: "9-16 LPA", senior: "18-30 LPA" },
    future: "High demand in Neuro-rehabilitation and Tele-therapy."
  },
  {
    id: "MED_018",
    title: "Pharmacovigilance Associate",
    category: "Medical & Healthcare",
    subCategory: "Pharma",
    after10: "Secondary School Education",
    after12: "B.Pharm / B.Sc",
    degree: "M.Pharm / Pharm.D",
    exams: ["GPAT"],
    skills: ["Drug Safety Reporting", "MedDRA Coding", "Clinical Database"],
    salary: { entry: "3.5-5.5 LPA", mid: "8-14 LPA", senior: "18-30 LPA" },
    future: "Increasing automation of safety data through AI/ML."
  },
  {
    id: "MED_019",
    title: "Dialysis Technician",
    category: "Medical & Healthcare",
    subCategory: "Paramedical",
    after10: "Diploma in Dialysis Tech",
    after12: "B.Sc in Renal Dialysis",
    degree: "B.Sc/M.Sc Renal Dialysis Technology",
    exams: ["State Paramedical Exam"],
    skills: ["Hemodialysis", "Patient Prep", "Machine Maintenance"],
    salary: { entry: "2-3.5 LPA", mid: "5-8 LPA", senior: "10-15 LPA" },
    future: "Expansion due to rising incidence of chronic kidney diseases."
  },
  {
    id: "MED_020",
    title: "Operation Theatre (OT) Technologist",
    category: "Medical & Healthcare",
    subCategory: "Paramedical",
    after10: "Diploma in OT Tech",
    after12: "B.Sc in OT Technology",
    degree: "B.Sc/M.Sc in OT Tech",
    exams: ["State level Paramedical"],
    skills: ["Sterilization", "Surgical Assistance", "Instrument Handling"],
    salary: { entry: "2.5-4 LPA", mid: "5-9 LPA", senior: "12-18 LPA" },
    future: "Transitioning toward Robotic OT management and high-tech CSSD."
  },
  {
    id: "MED_021",
    title: "Oncologist",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "DM/MCh in Oncology",
    exams: ["NEET-UG", "NEET-PG", "NEET-SS"],
    skills: ["Chemotherapy", "Radiation Planning", "Biopsy", "Cancer Genetics"],
    salary: { entry: "15-25 LPA", mid: "35-65 LPA", senior: "80 LPA - 2 Cr" },
    future: "Precision Medicine and Immunotherapy breakthroughs."
  },
  {
    id: "MED_022",
    title: "Psychiatrist",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "MD in Psychiatry",
    exams: ["NEET-UG", "NEET-PG"],
    skills: ["Psychotherapy", "Clinical Diagnosis", "Pharmacotherapy"],
    salary: { entry: "10-16 LPA", mid: "22-40 LPA", senior: "45-80 LPA" },
    future: "Growth in Digital Psychiatry and Neuromodulation treatments."
  },
  {
    id: "MED_023",
    title: "Medical Transcriptionist",
    category: "Medical & Healthcare",
    subCategory: "Administration",
    after10: "Secondary School Education",
    after12: "Any Graduation + MT Course",
    degree: "Certification in Medical Transcription",
    exams: ["Institute specific"],
    skills: ["Medical Terminology", "Typing Speed", "Listening Skills"],
    salary: { entry: "2.5-4 LPA", mid: "5-8 LPA", senior: "10-15 LPA" },
    future: "Transitioning into Medical Scribing and Voice-AI editing."
  },
  {
    id: "MED_024",
    title: "Clinical Research Coordinator",
    category: "Medical & Healthcare",
    subCategory: "Pharma",
    after10: "Secondary School Education",
    after12: "B.Pharm / B.Sc Biology",
    degree: "M.Sc Clinical Research",
    exams: ["NIPER JEE", "CUET"],
    skills: ["ICH-GCP Guidelines", "Data Collection", "Patient Recruiting"],
    salary: { entry: "3-6 LPA", mid: "8-15 LPA", senior: "18-32 LPA" },
    future: "India becoming a global hub for decentralized clinical trials."
  },
  {
    id: "MED_025",
    title: "Healthcare Data Analyst",
    category: "Medical & Healthcare",
    subCategory: "Administration",
    after10: "Secondary School Education",
    after12: "B.Sc IT / B.Pharm / B.E",
    degree: "MBA in Health Analytics or M.Sc Health Informatics",
    exams: ["CAT", "GATE"],
    skills: ["SQL", "Statistical Analysis", "EHR Management", "Python"],
    salary: { entry: "5-8 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "Massive demand for managing Ayushman Bharat digital health records."
  },
  {
    id: "MED_026",
    title: "Forensic Pathologist",
    category: "Medical & Healthcare",
    subCategory: "Diagnostics",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "MD in Forensic Medicine",
    exams: ["NEET-UG", "NEET-PG"],
    skills: ["Autopsy", "Legal Testimony", "DNA Fingerprinting"],
    salary: { entry: "10-15 LPA", mid: "18-30 LPA", senior: "35-60 LPA" },
    future: "Advancement in Virtual Autopsy (Virtopsy) and Toxicology."
  },
  {
    id: "MED_027",
    title: "Perfusionist",
    category: "Medical & Healthcare",
    subCategory: "Paramedical",
    after10: "Secondary School Education",
    after12: "B.Sc in Perfusion Technology",
    degree: "M.Sc in Perfusion Technology",
    exams: ["State Paramedical Boards"],
    skills: ["Heart-Lung Machine Operation", "ECMO", "Physiology Monitoring"],
    salary: { entry: "4-6 LPA", mid: "9-16 LPA", senior: "18-30 LPA" },
    future: "Crucial role in expanding Cardiac surgery centers across Tier-2 cities."
  },
  {
    id: "MED_028",
    title: "Obstetrician & Gynecologist",
    category: "Medical & Healthcare",
    subCategory: "Medicine",
    after10: "Secondary School Education",
    after12: "MBBS",
    degree: "MD/MS in OB-GYN",
    exams: ["NEET-UG", "NEET-PG"],
    skills: ["Prenatal Care", "Surgery", "Reproductive Health", "Labor Management"],
    salary: { entry: "12-18 LPA", mid: "25-50 LPA", senior: "60 LPA - 1.2 Cr" },
    future: "High specialization in IVF and Fetal Medicine."
  },
  {
    id: "MED_029",
    title: "Medical Coder",
    category: "Medical & Healthcare",
    subCategory: "Administration",
    after10: "Secondary School Education",
    after12: "B.Pharm / B.Sc / GNM",
    degree: "CPC (Certified Professional Coder) Certification",
    exams: ["AAPC Exam"],
    skills: ["ICD-10-CM", "CPT Coding", "Anatomy Knowledge"],
    salary: { entry: "3-5 LPA", mid: "6-10 LPA", senior: "12-20 LPA" },
    future: "Vital role in the growing Health Insurance sector in India."
  },
  {
    id: "MED_030",
    title: "Emergency Medical Technician (EMT)",
    category: "Medical & Healthcare",
    subCategory: "Paramedical",
    after10: "EMT Certification",
    after12: "B.Sc in Emergency Medical Technology",
    degree: "B.Sc/M.Sc in Emergency Medicine",
    exams: ["State Paramedical Boards"],
    skills: ["Triage", "First Aid", "Ambulance Equipment Ops", "Quick Response"],
    salary: { entry: "2.5-4 LPA", mid: "5-9 LPA", senior: "10-16 LPA" },
    future: "Integration with Smart Ambulance systems and 5G-linked tele-ER."
  },
  {
    id: "ENG_001",
    title: "Civil Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Civil Engineering",
    after12: "B.Tech/B.E. in Civil Engineering",
    degree: "B.Tech or M.Tech (Structural/Transportation)",
    exams: ["JEE Main", "GATE", "SSC JE"],
    skills: ["AutoCAD", "STAAD.Pro", "Project Management", "Structural Analysis"],
    salary: { entry: "3.5-6 LPA", mid: "10-18 LPA", senior: "22-45 LPA" },
    future: "Focus on Smart City infrastructure and sustainable green building materials."
  },
  {
    id: "ENG_002",
    title: "Mechanical Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Mechanical Engineering",
    after12: "B.Tech/B.E. in Mechanical Engineering",
    degree: "B.Tech or M.Tech (Design/Thermal)",
    exams: ["JEE Main", "GATE", "IES"],
    skills: ["SolidWorks", "Thermodynamics", "Ansys", "Manufacturing Processes"],
    salary: { entry: "3.5-7 LPA", mid: "9-16 LPA", senior: "20-40 LPA" },
    future: "Shift toward Industry 4.0, additive manufacturing (3D printing), and CNC automation."
  },
  {
    id: "ENG_003",
    title: "Electrical Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Electrical Engineering",
    after12: "B.Tech/B.E. in Electrical Engineering",
    degree: "B.Tech or M.Tech (Power Systems/Control)",
    exams: ["JEE Main", "GATE", "State PSC"],
    skills: ["Power Systems", "MATLAB", "Circuit Design", "PLC/SCADA"],
    salary: { entry: "4-7 LPA", mid: "10-20 LPA", senior: "25-50 LPA" },
    future: "Critical role in Smart Grid technology and renewable energy integration."
  },
  {
    id: "ENG_004",
    title: "Electronics & Communication Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in ECE",
    after12: "B.Tech/B.E. in ECE",
    degree: "B.Tech or M.Tech (VLSI/Embedded)",
    exams: ["JEE Main", "GATE", "IES"],
    skills: ["VLSI", "Signal Processing", "Embedded C", "Microcontrollers"],
    salary: { entry: "5-9 LPA", mid: "12-25 LPA", senior: "30-65 LPA" },
    future: "Massive growth in 5G/6G infrastructure and semiconductor manufacturing in India."
  },
  {
    id: "ENG_005",
    title: "Aeronautical Engineer",
    category: "Engineering",
    subCategory: "Aerospace",
    after10: "Secondary School Education",
    after12: "B.Tech in Aeronautical Engineering",
    degree: "B.Tech or M.Tech (Aerospace)",
    exams: ["JEE Advanced", "GATE", "AEEE"],
    skills: ["Aerodynamics", "Avionics", "Propulsion Systems", "CATIA"],
    salary: { entry: "6-10 LPA", mid: "15-28 LPA", senior: "35-70 LPA" },
    future: "Expanding private space sector (SpaceTech) and defense drone manufacturing."
  },
  {
    id: "ENG_006",
    title: "Chemical Engineer",
    category: "Engineering",
    subCategory: "Process Engineering",
    after10: "Diploma in Chemical Engineering",
    after12: "B.Tech/B.E. in Chemical Engineering",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE", "BITSAT"],
    skills: ["Unit Operations", "Aspen HYSYS", "Process Safety", "Thermodynamics"],
    salary: { entry: "4.5-8 LPA", mid: "12-22 LPA", senior: "28-55 LPA" },
    future: "Rising demand in Green Hydrogen production and Specialty Chemicals."
  },
  {
    id: "ENG_007",
    title: "Petroleum Engineer",
    category: "Engineering",
    subCategory: "Energy",
    after10: "Secondary School Education",
    after12: "B.Tech in Petroleum Engineering",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Drilling Engineering", "Reservoir Modeling", "Geology", "Safety Management"],
    salary: { entry: "7-12 LPA", mid: "18-35 LPA", senior: "40-90 LPA" },
    future: "Focus on EOR (Enhanced Oil Recovery) and transition to carbon capture."
  },
  {
    id: "ENG_008",
    title: "Biotechnology Engineer",
    category: "Engineering",
    subCategory: "Emerging Engineering",
    after10: "Secondary School Education",
    after12: "B.Tech in Biotechnology",
    degree: "B.Tech or M.Tech (Biotech)",
    exams: ["JEE Main", "GATE", "GAT-B"],
    skills: ["Genetic Engineering", "Bioinformatics", "Cell Culture", "Bioprocess"],
    salary: { entry: "4-7 LPA", mid: "9-18 LPA", senior: "20-45 LPA" },
    future: "Growth in biopharmaceuticals, vaccine research, and agricultural biotech."
  },
  {
    id: "ENG_009",
    title: "Automobile Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Automobile Engineering",
    after12: "B.Tech/B.E. in Automobile Engineering",
    degree: "B.Tech or M.Tech (Automotive Design)",
    exams: ["JEE Main", "GATE", "MET"],
    skills: ["Vehicle Dynamics", "IC Engines", "AutoCAD", "Testing & Analysis"],
    salary: { entry: "4-8 LPA", mid: "10-20 LPA", senior: "25-55 LPA" },
    future: "Rapid transition to Electric Vehicles (EV) and Autonomous driving tech."
  },
  {
    id: "ENG_010",
    title: "Robotics & Automation Engineer",
    category: "Engineering",
    subCategory: "Emerging Engineering",
    after10: "Diploma in Mechatronics",
    after12: "B.Tech in Robotics/Mechatronics",
    degree: "B.Tech or M.Tech (Robotics)",
    exams: ["JEE Main", "GATE", "SRMJEEE"],
    skills: ["ROS (Robot Operating System)", "C++", "Kinematics", "AI/ML"],
    salary: { entry: "5-9 LPA", mid: "14-26 LPA", senior: "30-60 LPA" },
    future: "Automation in warehouse logistics and collaborative robots (Cobots)."
  },
  {
    id: "ENG_011",
    title: "Environmental Engineer",
    category: "Engineering",
    subCategory: "Civil/Process",
    after10: "Diploma in Environmental Eng.",
    after12: "B.Tech in Civil/Environmental Engineering",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Waste Management", "EIA", "Water Treatment", "Air Quality Modeling"],
    salary: { entry: "4-6 LPA", mid: "8-15 LPA", senior: "18-35 LPA" },
    future: "Critical role in ESG compliance and Net-Zero carbon initiatives."
  },
  {
    id: "ENG_012",
    title: "Industrial Engineer",
    category: "Engineering",
    subCategory: "Management Engineering",
    after10: "Secondary School Education",
    after12: "B.Tech in Industrial/Production Engineering",
    degree: "B.Tech or M.Tech (Industrial Engineering)",
    exams: ["JEE Main", "GATE"],
    skills: ["Supply Chain", "Six Sigma", "Lean Manufacturing", "Operations Research"],
    salary: { entry: "5-8 LPA", mid: "12-22 LPA", senior: "25-50 LPA" },
    future: "Optimization of e-commerce supply chains and lean healthcare systems."
  },
  {
    id: "ENG_013",
    title: "Instrumentation Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Instrumentation",
    after12: "B.Tech/B.E. in Instrumentation & Control",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Control Systems", "PLC", "DCS", "Sensors & Transducers"],
    salary: { entry: "4-7 LPA", mid: "9-18 LPA", senior: "20-42 LPA" },
    future: "Crucial for automated process plants and IoT-enabled industrial sensing."
  },
  {
    id: "ENG_014",
    title: "Naval Architect / Marine Engineer",
    category: "Engineering",
    subCategory: "Marine",
    after10: "Secondary School Education",
    after12: "B.Tech in Marine Engineering / Naval Architecture",
    degree: "B.Tech or M.Tech",
    exams: ["IMU-CET", "JEE Main"],
    skills: ["Ship Design", "Hydrodynamics", "Marine Engines", "Navigation Systems"],
    salary: { entry: "6-12 LPA", mid: "18-35 LPA", senior: "40-80 LPA" },
    future: "Expansion in blue economy and autonomous cargo shipping."
  },
  {
    id: "ENG_015",
    title: "Mining Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Mining",
    after12: "B.Tech in Mining Engineering",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Explosives & Blasting", "Mine Ventilation", "Geotechnical Eng.", "Surveying"],
    salary: { entry: "6-10 LPA", mid: "15-28 LPA", senior: "30-60 LPA" },
    future: "Focus on sustainable mining and remote-operated mining equipment."
  },
  {
    id: "ENG_016",
    title: "Agricultural Engineer",
    category: "Engineering",
    subCategory: "Allied Engineering",
    after10: "Secondary School Education",
    after12: "B.Tech in Agricultural Engineering",
    degree: "B.Tech or M.Tech",
    exams: ["ICAR AIEEA", "JEE Main"],
    skills: ["Farm Machinery", "Irrigation Design", "Food Processing", "Soil Science"],
    salary: { entry: "3.5-6 LPA", mid: "8-15 LPA", senior: "18-35 LPA" },
    future: "Demand in Precision Farming, Drones in Agriculture, and Food Security."
  },
  {
    id: "ENG_017",
    title: "Textile Engineer",
    category: "Engineering",
    subCategory: "Manufacturing",
    after10: "Diploma in Textile Tech",
    after12: "B.Tech in Textile Technology",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Fiber Science", "Yarn Manufacture", "Fabric Design", "Dyeing & Printing"],
    salary: { entry: "3.5-6 LPA", mid: "8-15 LPA", senior: "18-35 LPA" },
    future: "Development of Smart Fabrics and technical textiles for healthcare/defense."
  },
  {
    id: "ENG_018",
    title: "Metallurgical Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Metallurgy",
    after12: "B.Tech in Metallurgy/Materials Engineering",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Extractive Metallurgy", "Material Characterization", "Corrosion Eng.", "Alloy Design"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-50 LPA" },
    future: "Innovating high-strength lightweight alloys for aerospace and EVs."
  },
  {
    id: "ENG_019",
    title: "Nuclear Engineer",
    category: "Engineering",
    subCategory: "Energy",
    after10: "Secondary School Education",
    after12: "B.Tech in Mechanical/Electrical (then specialisation)",
    degree: "M.Tech in Nuclear Engineering / BARC Training School",
    exams: ["GATE", "BARC OCES/DGFS"],
    skills: ["Reactor Physics", "Radiation Shielding", "Nuclear Safety", "Heat Transfer"],
    salary: { entry: "9-14 LPA", mid: "20-35 LPA", senior: "40-75 LPA" },
    future: "Growth in Small Modular Reactors (SMRs) and clean nuclear power."
  },
  {
    id: "ENG_020",
    title: "Software Engineer",
    category: "Engineering",
    subCategory: "Computer/IT",
    after10: "Diploma in Computer Science",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE", "VITEEE"],
    skills: ["Data Structures", "Algorithms", "Java/C++", "System Design"],
    salary: { entry: "6-12 LPA", mid: "18-35 LPA", senior: "40-90 LPA" },
    future: "Transition toward AI-first software development and edge computing."
  },
  {
    id: "ENG_021",
    title: "VLSI Design Engineer",
    category: "Engineering",
    subCategory: "Electronics",
    after10: "Secondary School Education",
    after12: "B.Tech in ECE/EE",
    degree: "M.Tech in VLSI Design",
    exams: ["GATE", "JEE Main"],
    skills: ["Verilog/VHDL", "CMOS Design", "Physical Design", "Cadence Tools"],
    salary: { entry: "8-15 LPA", mid: "22-45 LPA", senior: "50-1.2 Cr" },
    future: "Critical for India's Semicon Mission and chip-to-startup programs."
  },
  {
    id: "ENG_022",
    title: "Mechatronics Engineer",
    category: "Engineering",
    subCategory: "Emerging Engineering",
    after10: "Diploma in Mechatronics",
    after12: "B.Tech in Mechatronics",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE", "TNEA"],
    skills: ["Robotics", "Control Systems", "Mechanical Design", "Electronics"],
    salary: { entry: "5-9 LPA", mid: "12-25 LPA", senior: "28-55 LPA" },
    future: "Integration of smart sensors in medical devices and industrial machines."
  },
  {
    id: "ENG_023",
    title: "Nanotechnology Engineer",
    category: "Engineering",
    subCategory: "Emerging Engineering",
    after10: "Secondary School Education",
    after12: "B.Tech in Nanotechnology",
    degree: "M.Tech or Ph.D.",
    exams: ["JEE Main", "GATE"],
    skills: ["Nanomaterials", "Scanning Electron Microscopy", "Microfabrication"],
    salary: { entry: "5-10 LPA", mid: "12-25 LPA", senior: "30-60 LPA" },
    future: "Applications in targeted drug delivery and high-efficiency solar cells."
  },
  {
    id: "ENG_024",
    title: "Data Center Engineer",
    category: "Engineering",
    subCategory: "IT/Infrastructure",
    after10: "Diploma in EE/CS",
    after12: "B.Tech in EE/CS/IT",
    degree: "B.Tech + Certifications (CDCP)",
    exams: ["JEE Main", "GATE"],
    skills: ["Cooling Systems", "Power Backup", "Networking", "Server Management"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-45 LPA" },
    future: "India becoming a global data center hub requires massive infra engineering."
  },
  {
    id: "ENG_025",
    title: "Renewable Energy Engineer",
    category: "Engineering",
    subCategory: "Energy",
    after10: "Diploma in RE",
    after12: "B.Tech in EE/Mechanical/Energy Engineering",
    degree: "M.Tech in Renewable Energy",
    exams: ["JEE Main", "GATE"],
    skills: ["Solar PV Design", "Wind Turbine Tech", "Energy Auditing", "Bioenergy"],
    salary: { entry: "4.5-8 LPA", mid: "10-20 LPA", senior: "25-50 LPA" },
    future: "Key role in meeting India's 500GW renewable energy target by 2030."
  },
  {
    id: "ENG_026",
    title: "Production Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Production Eng.",
    after12: "B.Tech in Production/Mechanical",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["CIM", "Quality Control", "Machining", "Work Study"],
    salary: { entry: "4-7 LPA", mid: "9-16 LPA", senior: "20-40 LPA" },
    future: "Integration of digital twins in manufacturing production lines."
  },
  {
    id: "ENG_027",
    title: "Biomedical Instrumentation Engineer",
    category: "Engineering",
    subCategory: "Healthcare Engineering",
    after10: "Diploma in Biomedical",
    after12: "B.Tech in Biomedical/Instrumentation",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Medical Imaging", "Signal Acquisition", "Safety Standards", "Calibration"],
    salary: { entry: "4-7 LPA", mid: "9-18 LPA", senior: "20-40 LPA" },
    future: "Growth in high-end medical diagnostic equipment manufacturing in India."
  },
  {
    id: "ENG_028",
    title: "Cloud Infrastructure Engineer",
    category: "Engineering",
    subCategory: "IT/Systems",
    after10: "Diploma in CS",
    after12: "B.Tech in CS/IT",
    degree: "B.Tech + Cloud Certs (AWS/Azure)",
    exams: ["JEE Main", "MET"],
    skills: ["Virtualization", "Networking", "Security", "Infrastructure as Code"],
    salary: { entry: "6-11 LPA", mid: "15-28 LPA", senior: "30-60 LPA" },
    future: "Supporting the backbone of India's digital public infrastructure (UPI/ONDC)."
  },
  {
    id: "ENG_029",
    title: "Safety Engineer",
    category: "Engineering",
    subCategory: "Core Engineering",
    after10: "Diploma in Safety Eng.",
    after12: "B.Tech in any engineering + Safety Diploma",
    degree: "B.Tech in Fire & Safety Engineering",
    exams: ["TNEA", "CUSAT CAT"],
    skills: ["Risk Assessment", "Fire Safety", "OSHA/HSE Standards", "Auditing"],
    salary: { entry: "4-7 LPA", mid: "10-18 LPA", senior: "20-45 LPA" },
    future: "Mandatory requirement in rising manufacturing and chemical hubs."
  },
  {
    id: "ENG_030",
    title: "Materials Scientist / Engineer",
    category: "Engineering",
    subCategory: "Emerging Engineering",
    after10: "Secondary School Education",
    after12: "B.Tech in Materials Science",
    degree: "B.Tech or M.Tech",
    exams: ["JEE Main", "GATE"],
    skills: ["Polymers", "Ceramics", "Composite Materials", "Testing"],
    salary: { entry: "5-9 LPA", mid: "12-25 LPA", senior: "28-55 LPA" },
    future: "Designing next-gen battery materials for energy storage and space travel."
  },
  {
    id: "FIN_001",
    title: "Chartered Accountant (CA)",
    category: "Commerce & Finance",
    subCategory: "Tax & Audit",
    after10: "Secondary School Education",
    after12: "CA Foundation",
    degree: "ICAI Membership (ACA/FCA)",
    exams: ["CA Foundation", "CA Intermediate", "CA Final"],
    skills: ["Auditing", "Taxation", "Financial Reporting", "Strategic Management"],
    salary: { entry: "8-12 LPA", mid: "18-28 LPA", senior: "35-70 LPA" },
    future: "Increasing focus on ESG Reporting, Forensic Auditing, and International Taxation."
  },
  {
    id: "FIN_002",
    title: "Investment Banker",
    category: "Commerce & Finance",
    subCategory: "Investment",
    after10: "Secondary School Education",
    after12: "B.Com / BBA / BMS",
    degree: "MBA Finance / CFA / MS Finance",
    exams: ["CAT", "CFA Level I/II/III", "NISM Series"],
    skills: ["Financial Modeling", "Valuation", "M&A", "Deal Structuring"],
    salary: { entry: "10-20 LPA", mid: "30-60 LPA", senior: "80 LPA - 2 Cr" },
    future: "Growth in tech-driven IPOs and cross-border Private Equity deals."
  },
  {
    id: "FIN_003",
    title: "Company Secretary (CS)",
    category: "Commerce & Finance",
    subCategory: "Corporate Law",
    after10: "Secondary School Education",
    after12: "CSEET (Entrance)",
    degree: "ICSI Membership (ACS/FCS)",
    exams: ["CSEET", "CS Executive", "CS Professional"],
    skills: ["Corporate Governance", "Compliance Management", "Legal Advisory"],
    salary: { entry: "5-8 LPA", mid: "12-20 LPA", senior: "25-50 LPA" },
    future: "Rising demand for legal compliance in startups and digital asset regulation."
  },
  {
    id: "FIN_004",
    title: "Cost & Management Accountant (CMA)",
    category: "Commerce & Finance",
    subCategory: "Cost Management",
    after10: "Secondary School Education",
    after12: "CMA Foundation",
    degree: "ICMAI Membership (ACMA/FCMA)",
    exams: ["CMA Foundation", "CMA Intermediate", "CMA Final"],
    skills: ["Cost Auditing", "Budgetary Control", "Pricing Analysis"],
    salary: { entry: "6-10 LPA", mid: "14-22 LPA", senior: "25-45 LPA" },
    future: "Expanding into Supply Chain Finance and Lean Cost Management in manufacturing."
  },
  {
    id: "FIN_005",
    title: "Actuary",
    category: "Commerce & Finance",
    subCategory: "Insurance",
    after10: "Secondary School Education",
    after12: "B.Sc Statistics/Maths or B.Com",
    degree: "Fellowship of IAI (Institute of Actuaries of India)",
    exams: ["ACET", "IAI Core Principles Exams"],
    skills: ["Risk Assessment", "Probability", "Statistical Modeling"],
    salary: { entry: "8-12 LPA", mid: "20-40 LPA", senior: "50 LPA - 1.2 Cr" },
    future: "High demand in Climate Risk insurance and Cyber Risk modeling."
  },
  {
    id: "FIN_006",
    title: "Equity Research Analyst",
    category: "Commerce & Finance",
    subCategory: "Investment",
    after10: "Secondary School Education",
    after12: "B.Com / B.A. Economics",
    degree: "CFA / MBA Finance",
    exams: ["NISM XV", "CFA"],
    skills: ["Fundamental Analysis", "Sector Research", "Report Writing"],
    salary: { entry: "5-9 LPA", mid: "12-25 LPA", senior: "30-55 LPA" },
    future: "AI-integrated stock forecasting and ESG-focused equity research."
  },
  {
    id: "FIN_007",
    title: "Financial Risk Manager",
    category: "Commerce & Finance",
    subCategory: "Risk Management",
    after10: "Secondary School Education",
    after12: "Any Graduation",
    degree: "FRM (GARP) Certification",
    exams: ["FRM Part I & II"],
    skills: ["Market Risk", "Credit Risk", "Operational Risk Management"],
    salary: { entry: "7-12 LPA", mid: "18-32 LPA", senior: "40-75 LPA" },
    future: "Critical roles in managing volatile global markets and Fintech security."
  },
  {
    id: "FIN_008",
    title: "Tax Consultant",
    category: "Commerce & Finance",
    subCategory: "Tax",
    after10: "Secondary School Education",
    after12: "B.Com / BBA",
    degree: "M.Com / LLB / CA",
    exams: ["UGC NET", "CA/CS Exams"],
    skills: ["GST Laws", "Income Tax Compliance", "Tax Planning"],
    salary: { entry: "4-7 LPA", mid: "10-18 LPA", senior: "22-45 LPA" },
    future: "Transitioning to Digital Tax administration and International Tax treaties."
  },
  {
    id: "FIN_009",
    title: "Wealth Manager",
    category: "Commerce & Finance",
    subCategory: "Banking & Finance",
    after10: "Secondary School Education",
    after12: "B.Com / BMS",
    degree: "CFP (Certified Financial Planner) / MBA",
    exams: ["CFP Certification", "NISM Series X-A/B"],
    skills: ["Portfolio Management", "Estate Planning", "Relationship Management"],
    salary: { entry: "6-10 LPA", mid: "15-28 LPA", senior: "35-75 LPA" },
    future: "Shift toward 'Hybrid Advisory' combining AI-Robo Advisors with human empathy."
  },
  {
    id: "FIN_010",
    title: "FinTech Specialist",
    category: "Commerce & Finance",
    subCategory: "Analytics",
    after10: "Secondary School Education",
    after12: "B.Com / B.Sc IT / BBA",
    degree: "M.Sc FinTech / PG in Digital Finance",
    exams: ["Institute specific"],
    skills: ["Blockchain", "Digital Payments", "Data Visualization", "Python"],
    salary: { entry: "7-13 LPA", mid: "18-35 LPA", senior: "45-90 LPA" },
    future: "Leading the revolution in CBDCs (Digital Rupee) and Open Banking."
  },
  {
    id: "FIN_011",
    title: "Business Analyst",
    category: "Commerce & Finance",
    subCategory: "Analytics",
    after10: "Secondary School Education",
    after12: "B.Com / BBA / B.E.",
    degree: "MBA Business Analytics / PGDM",
    exams: ["CAT", "XAT", "GMAT"],
    skills: ["SQL", "Tableau", "Agile Methodology", "Process Mapping"],
    salary: { entry: "5-9 LPA", mid: "12-22 LPA", senior: "25-50 LPA" },
    future: "Bridging the gap between core business and automated AI solutions."
  },
  {
    id: "FIN_012",
    title: "Treasury Manager",
    category: "Commerce & Finance",
    subCategory: "Banking & Finance",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "MBA Finance / CA",
    exams: ["CA Final", "CAT"],
    skills: ["Liquidity Management", "Forex Hedging", "Cash Flow Forecasting"],
    salary: { entry: "8-14 LPA", mid: "20-35 LPA", senior: "45-85 LPA" },
    future: "Managing global liquidity in real-time using blockchain-based settlements."
  },
  {
    id: "FIN_013",
    title: "Credit Analyst",
    category: "Commerce & Finance",
    subCategory: "Banking",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "MBA Finance / CA",
    exams: ["IBPS PO", "SBI PO", "CA Exams"],
    skills: ["Balance Sheet Analysis", "Credit Appraisal", "Ratio Analysis"],
    salary: { entry: "5-9 LPA", mid: "12-20 LPA", senior: "25-45 LPA" },
    future: "Utilizing Alternative Data and Machine Learning for credit scoring."
  },
  {
    id: "FIN_014",
    title: "Portfolio Manager",
    category: "Commerce & Finance",
    subCategory: "Investment",
    after10: "Secondary School Education",
    after12: "B.Com / B.A. Economics",
    degree: "CFA / MBA Finance",
    exams: ["CFA Level III", "NISM Series XXI-A"],
    skills: ["Asset Allocation", "Risk-Adjusted Returns", "Market Strategy"],
    salary: { entry: "12-18 LPA", mid: "30-55 LPA", senior: "70 LPA - 1.5 Cr" },
    future: "Focus on Alts (Alternative Investments) and algorithmic portfolio rebalancing."
  },
  {
    id: "FIN_015",
    title: "Internal Auditor",
    category: "Commerce & Finance",
    subCategory: "Tax & Audit",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "CIA (Certified Internal Auditor) / CA",
    exams: ["CIA Exam", "CA Exams"],
    skills: ["Risk Control", "Governance", "Internal Check Systems"],
    salary: { entry: "6-10 LPA", mid: "15-25 LPA", senior: "30-60 LPA" },
    future: "Shift to 'Continuous Auditing' using real-time data monitoring tools."
  },
  {
    id: "FIN_016",
    title: "Management Consultant (Finance)",
    category: "Commerce & Finance",
    subCategory: "Strategy",
    after10: "Secondary School Education",
    after12: "B.Com / BBA (Top Tier)",
    degree: "MBA from Top B-Schools",
    exams: ["CAT", "GMAT"],
    skills: ["Problem Solving", "Business Modeling", "Client Management"],
    salary: { entry: "15-25 LPA", mid: "35-60 LPA", senior: "80 LPA - 1.8 Cr" },
    future: "Guiding Indian MNCs through digital and green business transformations."
  },
  {
    id: "FIN_017",
    title: "Insurance Underwriter",
    category: "Commerce & Finance",
    subCategory: "Insurance",
    after10: "Secondary School Education",
    after12: "B.Com / BBA",
    degree: "Diploma in Insurance (III)",
    exams: ["III Licentiate/Associate"],
    skills: ["Risk Evaluation", "Policy Documentation", "Analytical Thinking"],
    salary: { entry: "4-6 LPA", mid: "9-15 LPA", senior: "18-35 LPA" },
    future: "Automation of routine underwriting using AI and IoT data inputs."
  },
  {
    id: "FIN_018",
    title: "Quantitative Analyst (Quant)",
    category: "Commerce & Finance",
    subCategory: "Investment",
    after10: "Secondary School Education",
    after12: "B.Sc Maths/Stats or B.Tech",
    degree: "Master in Quantitative Finance",
    exams: ["GATE", "CFA", "CQF"],
    skills: ["Python/R", "Algorithmic Trading", "Calculus"],
    salary: { entry: "12-22 LPA", mid: "35-70 LPA", senior: "80 LPA - 2 Cr" },
    future: "Rise of HFT (High-Frequency Trading) and quantitative hedge funds in India."
  },
  {
    id: "FIN_019",
    title: "Forensic Accountant",
    category: "Commerce & Finance",
    subCategory: "Tax & Audit",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "CA + CFE (Certified Fraud Examiner)",
    exams: ["CFE Exam", "CA Final"],
    skills: ["Fraud Detection", "Legal Knowledge", "Investigative Auditing"],
    salary: { entry: "8-13 LPA", mid: "18-30 LPA", senior: "35-75 LPA" },
    future: "Combating sophisticated financial crimes in the crypto and digital space."
  },
  {
    id: "FIN_020",
    title: "Investment Advisor",
    category: "Commerce & Finance",
    subCategory: "Investment",
    after10: "Secondary School Education",
    after12: "B.Com / BBA",
    degree: "NISM Certification / CFP",
    exams: ["NISM Series X-A & X-B"],
    skills: ["Financial Planning", "Market Trends", "Communication"],
    salary: { entry: "4-7 LPA", mid: "9-16 LPA", senior: "20-40 LPA" },
    future: "Growth in SEBI Registered Investment Advisor (RIA) practices."
  },
  {
    id: "FIN_021",
    title: "ESG Analyst (Finance)",
    category: "Commerce & Finance",
    subCategory: "Analytics",
    after10: "Secondary School Education",
    after12: "B.Com / B.A. Economics",
    degree: "CFA (ESG Specialization)",
    exams: ["CFA ESG Certificate"],
    skills: ["Sustainability Reporting", "Green Bonds", "Regulatory Compliance"],
    salary: { entry: "7-12 LPA", mid: "15-28 LPA", senior: "35-65 LPA" },
    future: "Mandatory requirement as SEBI tightens BRSR (Sustainability) reporting."
  },
  {
    id: "FIN_022",
    title: "Financial Controller",
    category: "Commerce & Finance",
    subCategory: "Banking & Finance",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "CA / CPA / MBA Finance",
    exams: ["CA Final"],
    skills: ["Internal Controls", "Financial Strategy", "Team Leadership"],
    salary: { entry: "15-25 LPA", mid: "30-55 LPA", senior: "60 LPA - 1.5 Cr" },
    future: "Evolving into a strategic partner role for CEO/CFO office."
  },
  {
    id: "FIN_023",
    title: "Venture Capital Analyst",
    category: "Commerce & Finance",
    subCategory: "Investment",
    after10: "Secondary School Education",
    after12: "B.Com / B.Tech (Top Tier)",
    degree: "MBA Finance / CFA",
    exams: ["CAT", "GMAT"],
    skills: ["Due Diligence", "Market Mapping", "Startup Valuation"],
    salary: { entry: "10-18 LPA", mid: "25-45 LPA", senior: "60 LPA - 2 Cr" },
    future: "Focus on Deep-Tech, Climate-Tech, and Agritech startup ecosystems."
  },
  {
    id: "FIN_024",
    title: "Merchant Banker",
    category: "Commerce & Finance",
    subCategory: "Banking",
    after10: "Secondary School Education",
    after12: "B.Com / LLB",
    degree: "MBA Finance / CA / LLB",
    exams: ["NISM Series IX"],
    skills: ["IPO Management", "Underwriting", "Capital Raising"],
    salary: { entry: "8-14 LPA", mid: "18-35 LPA", senior: "45-90 LPA" },
    future: "Increasing activity in SME IPOs and Rights Issues in Indian markets."
  },
  {
    id: "FIN_025",
    title: "Corporate Finance Manager",
    category: "Commerce & Finance",
    subCategory: "Banking & Finance",
    after10: "Secondary School Education",
    after12: "B.Com / BBA",
    degree: "MBA Finance / CA",
    exams: ["CA Final", "CAT"],
    skills: ["Capital Budgeting", "Working Capital", "Fundraising"],
    salary: { entry: "9-15 LPA", mid: "20-38 LPA", senior: "45-95 LPA" },
    future: "Strategic capital allocation in a high-growth Indian economy."
  },
  {
    id: "FIN_026",
    title: "Compliance Officer",
    category: "Commerce & Finance",
    subCategory: "Corporate Law",
    after10: "Secondary School Education",
    after12: "B.Com / LLB",
    degree: "CS / LLB",
    exams: ["CS Final", "All India Bar Exam"],
    skills: ["Regulatory Knowledge", "Ethical Standards", "Risk Mitigation"],
    salary: { entry: "5-8 LPA", mid: "12-22 LPA", senior: "25-50 LPA" },
    future: "High demand in Fintech and Cryptocurency exchange compliance."
  },
  {
    id: "FIN_027",
    title: "Financial Data Scientist",
    category: "Commerce & Finance",
    subCategory: "Analytics",
    after10: "Secondary School Education",
    after12: "B.Com (Maths) / B.Sc Stats",
    degree: "M.Sc Data Science / MBA Finance",
    exams: ["Institute specific"],
    skills: ["Machine Learning", "Big Data", "Predictive Modeling"],
    salary: { entry: "10-18 LPA", mid: "25-45 LPA", senior: "55-1.2 Cr" },
    future: "Redefining fraud detection and algorithmic customer profiling in banking."
  },
  {
    id: "FIN_028",
    title: "International Tax Specialist",
    category: "Commerce & Finance",
    subCategory: "Tax",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "CA / ADIT (CIOT UK)",
    exams: ["CA Final", "ADIT"],
    skills: ["Transfer Pricing", "Double Tax Treaties", "Cross-Border Tax"],
    salary: { entry: "10-16 LPA", mid: "22-40 LPA", senior: "45-90 LPA" },
    future: "Navigating Pillar 2 (Global Minimum Tax) for Indian MNCs."
  },
  {
    id: "FIN_029",
    title: "Retail Banker",
    category: "Commerce & Finance",
    subCategory: "Banking",
    after10: "Secondary School Education",
    after12: "B.Com / BBA",
    degree: "MBA Finance / JAIIB / CAIIB",
    exams: ["IBPS PO", "SBI PO"],
    skills: ["Customer Service", "Product Sales", "Banking Operations"],
    salary: { entry: "4-7 LPA", mid: "10-18 LPA", senior: "20-40 LPA" },
    future: "Evolving toward 'Phygital' banking (Physical + Digital) expertise."
  },
  {
    id: "FIN_030",
    title: "Chief Financial Officer (CFO)",
    category: "Commerce & Finance",
    subCategory: "Strategy",
    after10: "Secondary School Education",
    after12: "B.Com",
    degree: "CA / MBA Finance (Top B-School)",
    exams: ["CA Final", "CAT"],
    skills: ["Visionary Leadership", "Investor Relations", "Capital Structure"],
    salary: { entry: "N/A (Senior Only)", mid: "50-90 LPA", senior: "1.5 - 10 Cr" },
    future: "The 'Co-Pilot' to the CEO, focusing on digital transformation and growth."
  }
];
